const businesses = [
  {
    id: '1',
    name: 'Soweto Seafood Restaurant',
    type: 'Food & Beverage',
    description: 'A seafood haven offering the freshest catches from the ocean.',
    location: '-26.2283, 27.8981',
    cover_img: '.',
    menu: [
      { item: 'Grilled Kingklip', price: 'R120', description: 'Freshly grilled kingklip served with a lemon butter sauce.' },
      { item: 'Calamari Rings', price: 'R70', description: 'Crispy fried calamari rings with a tangy dipping sauce.' },
      { item: 'Seafood Platter', price: 'R220', description: 'A mixed platter with prawns, mussels, and hake.' },
      { item: 'Fish & Chips', price: 'R80', description: 'Classic fish and chips, lightly battered and fried to perfection.' },
    ],
    openingHours: 'Monday - Sunday: 11 AM - 9 PM',
    contact: '012 345 6789',
    website: 'http://sowetoseafoodrestaurant.com',
  },
  {
    id: '2',
    name: 'Orlando West Italian Bistro',
    type: 'Food & Beverage',
    description: 'A charming bistro offering authentic Italian pasta and pizzas.',
    location: '-26.2295, 27.9005',
    cover_img: '.',
    menu: [
      { item: 'Margherita Pizza', price: 'R80', description: 'A classic pizza topped with fresh tomatoes, mozzarella, and basil.' },
      { item: 'Lasagna', price: 'R95', description: 'Layers of pasta, rich tomato sauce, and melted cheese.' },
      { item: 'Spaghetti Bolognese', price: 'R85', description: 'Classic pasta with a rich meat sauce.' },
      { item: 'Tiramisu', price: 'R55', description: 'A traditional Italian dessert made with coffee-soaked ladyfingers and mascarpone cream.' },
    ],
    openingHours: 'Monday - Sunday: 10 AM - 10 PM',
    contact: '011 456 7890',
    website: 'http://orlandowestitalianbistro.com',
  },
  {
    id: '3',
    name: 'Soweto Vegan Café',
    type: 'Food & Beverage',
    description: 'A café serving healthy and delicious vegan meals.',
    location: '-26.2305, 27.8984',
    cover_img: '.',
    menu: [
      { item: 'Vegan Burger', price: 'R70', description: 'A plant-based patty served with lettuce, tomato, and vegan mayo.' },
      { item: 'Tofu Stir-Fry', price: 'R85', description: 'Stir-fried tofu with a mix of colorful vegetables and a soy-based sauce.' },
      { item: 'Chickpea Salad', price: 'R60', description: 'A refreshing salad with chickpeas, avocado, and a lemon-tahini dressing.' },
      { item: 'Vegan Smoothie Bowl', price: 'R50', description: 'A blended fruit smoothie topped with granola, chia seeds, and coconut flakes.' },
    ],
    openingHours: 'Monday - Saturday: 8 AM - 8 PM, Sunday: Closed',
    contact: '012 678 9101',
    website: 'http://sowetovegancafe.com',
  },
  {
    id: '4',
    name: 'Orlando West Sushi House',
    type: 'Food & Beverage',
    description: 'A cozy sushi spot offering fresh sushi and sashimi.',
    location: '-26.2312, 27.8990',
    cover_img: '.',
    menu: [
      { item: 'California Roll', price: 'R80', description: 'Rolls filled with crab, avocado, and cucumber, topped with sesame seeds.' },
      { item: 'Salmon Sashimi', price: 'R95', description: 'Fresh, thinly sliced salmon served with soy sauce and wasabi.' },
      { item: 'Spicy Tuna Roll', price: 'R85', description: 'Tuna mixed with spicy mayo, wrapped in nori and rice.' },
      { item: 'Tempura Prawns', price: 'R75', description: 'Crispy battered prawns served with a sweet soy sauce.' },
    ],
    openingHours: 'Monday - Sunday: 12 PM - 9 PM',
    contact: '010 234 5678',
    website: 'http://orlandowestsushihouse.com',
  },
  {
    id: '5',
    name: 'Soweto Steakhouse',
    type: 'Food & Beverage',
    description: 'A premium steakhouse specializing in perfectly cooked steaks.',
    location: '-26.2320, 27.8983',
    cover_img: '.',
    menu: [
      { item: 'Rib-eye Steak', price: 'R180', description: 'A tender rib-eye steak grilled to your preference.' },
      { item: 'Fillet Mignon', price: 'R220', description: 'A lean and tender fillet steak, served with a side of creamy peppercorn sauce.' },
      { item: 'Steak and Chips', price: 'R150', description: 'A juicy steak served with crispy fries and a side salad.' },
      { item: 'Chicken Schnitzel', price: 'R130', description: 'Breaded chicken schnitzel, served with mashed potatoes and gravy.' },
    ],
    openingHours: 'Monday - Sunday: 11 AM - 10 PM',
    contact: '013 789 0123',
    website: 'http://sowetosteakhouse.com',
  },
  {
    id: '6',
    name: 'Orlando West Mediterranean Grill',
    type: 'Food & Beverage',
    description: 'A grill serving Mediterranean-style dishes, with a focus on fresh ingredients.',
    location: '-26.2335, 27.8977',
    cover_img: '.',
    menu: [
      { item: 'Chicken Souvlaki', price: 'R95', description: 'Grilled chicken skewers served with pita and tzatziki sauce.' },
      { item: 'Falafel Wrap', price: 'R70', description: 'Crispy falafel balls wrapped in pita bread with lettuce and tahini sauce.' },
      { item: 'Lamb Shawarma', price: 'R110', description: 'Slow-cooked lamb served in pita bread with garlic sauce and pickled vegetables.' },
      { item: 'Hummus with Pita', price: 'R45', description: 'Smooth hummus served with fresh pita bread.' },
    ],
    openingHours: 'Monday - Sunday: 10 AM - 10 PM',
    contact: '014 345 6789',
    website: 'http://orlandowestmediterraneangrill.com',
  },
  {
    id: '7',
    name: 'Soweto Mexican Fiesta',
    type: 'Food & Beverage',
    description: 'A vibrant Mexican restaurant offering traditional dishes and margaritas.',
    location: '-26.2348, 27.8962',
    cover_img: '.',
    menu: [
      { item: 'Tacos', price: 'R60', description: 'Soft corn tortillas filled with beef, chicken, or vegetables, topped with salsa and guacamole.' },
      { item: 'Burrito', price: 'R95', description: 'A large flour tortilla filled with your choice of meat, rice, beans, and cheese.' },
      { item: 'Enchiladas', price: 'R100', description: 'Rolled tortillas filled with chicken or beef, smothered in spicy red sauce and cheese.' },
      { item: 'Churros', price: 'R40', description: 'Fried dough sticks dusted with cinnamon sugar, served with chocolate sauce.' },
    ],
    openingHours: 'Monday - Sunday: 11 AM - 9 PM',
    contact: '015 456 7890',
    website: 'http://sowetomexicanfiesta.com',
  },
  {
    id: '8',
    name: 'Orlando West Burger Joint',
    type: 'Food & Beverage',
    description: 'A burger spot offering a variety of gourmet burgers.',
    location: '-26.2355, 27.8958',
    cover_img: '.',
    menu: [
      { item: 'Classic Cheeseburger', price: 'R70', description: 'A juicy beef patty topped with cheddar cheese, lettuce, and tomato.' },
      { item: 'Bacon BBQ Burger', price: 'R95', description: 'Beef patty with crispy bacon, BBQ sauce, and fried onions.' },
      { item: 'Vegetarian Burger', price: 'R75', description: 'A plant-based patty with lettuce, tomato, and vegan mayo.' },
      { item: 'Fries', price: 'R30', description: 'Crispy golden fries served with ketchup or aioli.' },
    ],
    openingHours: 'Monday - Sunday: 12 PM - 10 PM',
    contact: '016 789 0123',
    website: 'http://orlandowestburgerjoint.com',
  },
  {
    id: '9',
    name: 'Soweto Tapas & Wine Bar',
    type: 'Food & Beverage',
    description: 'A cozy spot offering small plates and a wide selection of wines.',
    location: '-26.2360, 27.8974',
    cover_img: '.',
    menu: [
      { item: 'Patatas Bravas', price: 'R60', description: 'Crispy potatoes served with a spicy tomato sauce.' },
      { item: 'Chorizo', price: 'R85', description: 'Grilled Spanish sausage served with a garlic aioli.' },
      { item: 'Olives and Cheese Platter', price: 'R120', description: 'A selection of olives, cheeses, and crackers.' },
      { item: 'Shrimp Croquettes', price: 'R95', description: 'Golden fried croquettes filled with shrimp and béchamel sauce.' },
    ],
    openingHours: 'Monday - Sunday: 4 PM - 12 AM',
    contact: '017 456 7890',
    website: 'http://sowetotapaswinebar.com',
  },
  {
    id: '10',
    name: 'Orlando West Bar & Grill',
    type: 'Food & Beverage',
    description: 'A lively bar offering grilled meats and hearty sides.',
    location: '-26.2373, 27.8968',
    cover_img: '.',
    menu: [
      { item: 'BBQ Ribs', price: 'R150', description: 'Tender ribs coated in BBQ sauce, served with coleslaw and fries.' },
      { item: 'Grilled Chicken', price: 'R120', description: 'Grilled chicken breast served with a side of vegetables and rice.' },
      { item: 'Beef Kebabs', price: 'R100', description: 'Marinated beef skewers grilled and served with pita bread.' },
      { item: 'Caesar Salad', price: 'R55', description: 'Crisp lettuce, chicken, bacon, and croutons, tossed in Caesar dressing.' },
    ],
    openingHours: 'Monday - Sunday: 12 PM - 10 PM',
    contact: '018 789 0123',
    website: 'http://orlandowestbargrill.com',
  },
  {
    id: '11',
    name: 'Soweto Bistro & Café',
    type: 'Food & Beverage',
    description: 'A cozy bistro offering a mix of European and local dishes.',
    location: '-26.2384, 27.8951',
    cover_img: '.',
    menu: [
      { item: 'Chicken Alfredo', price: 'R110', description: 'Creamy Alfredo sauce with grilled chicken and pasta.' },
      { item: 'Beef Stew', price: 'R120', description: 'Tender beef slow-cooked with vegetables and served with rice.' },
      { item: 'Vegetable Stir-fry', price: 'R85', description: 'Seasonal vegetables stir-fried in a soy-based sauce.' },
      { item: 'Apple Pie', price: 'R50', description: 'Homemade apple pie served with vanilla ice cream.' },
    ],
    openingHours: 'Monday - Sunday: 9 AM - 9 PM',
    contact: '019 567 8901',
    website: 'http://sowetobistrocafe.com',
  },
  {
    id: '12',
    name: 'Orlando West Chinese Takeaway',
    type: 'Food & Beverage',
    description: 'A Chinese takeaway offering traditional stir-fried dishes and noodles.',
    location: '-26.2396, 27.8945',
    cover_img: '.',
    menu: [
      { item: 'Sweet and Sour Chicken', price: 'R80', description: 'Crispy chicken pieces coated in a sweet and sour sauce.' },
      { item: 'Chow Mein', price: 'R70', description: 'Stir-fried noodles with vegetables and your choice of meat.' },
      { item: 'Spring Rolls', price: 'R50', description: 'Crispy rolls stuffed with vegetables and served with sweet chili sauce.' },
      { item: 'Fried Rice', price: 'R45', description: 'Stir-fried rice with vegetables, eggs, and a soy-based sauce.' },
    ],
    openingHours: 'Monday - Sunday: 11 AM - 10 PM',
    contact: '020 234 5678',
    website: 'http://orlandowestchinesetakeaway.com',
  },
  {
    id: '13',
    name: 'Soweto Pancake House',
    type: 'Food & Beverage',
    description: 'A sweet and savory pancake house offering a variety of fillings.',
    location: '-26.2401, 27.8937',
    cover_img: '.',
    menu: [
      { item: 'Banana Pancakes', price: 'R55', description: 'Soft pancakes filled with fresh bananas and topped with syrup.' },
      { item: 'Nutella Pancakes', price: 'R60', description: 'Pancakes filled with creamy Nutella and powdered sugar.' },
      { item: 'Savory Chicken Pancakes', price: 'R70', description: 'Pancakes filled with grilled chicken, mushrooms, and cheese.' },
      { item: 'Cheese & Ham Pancakes', price: 'R65', description: 'Pancakes filled with melted cheese and ham.' },
    ],
    openingHours: 'Monday - Sunday: 8 AM - 8 PM',
    contact: '021 678 9101',
    website: 'http://sowetopancakehouse.com',
  },
  {
    id: '14',
    name: 'Orlando West Pizzeria',
    type: 'Food & Beverage',
    description: 'A family-friendly pizzeria offering wood-fired pizzas.',
    location: '-26.2410, 27.8929',
    cover_img: '.',
    menu: [
      { item: 'Pepperoni Pizza', price: 'R85', description: 'Wood-fired pizza topped with pepperoni, mozzarella, and tomato sauce.' },
      { item: 'Vegetarian Pizza', price: 'R80', description: 'Topped with fresh vegetables like mushrooms, peppers, and olives.' },
      { item: 'Marinara Pizza', price: 'R90', description: 'Pizza topped with fresh seafood, garlic, and herbs.' },
      { item: 'Garlic Bread', price: 'R40', description: 'Freshly baked garlic bread with butter and herbs.' },
    ],
    openingHours: 'Monday - Sunday: 11 AM - 11 PM',
    contact: '022 345 6789',
    website: 'http://orlandowestpizzeria.com',
  },
  {
    id: '15',
    name: 'Soweto Bakery',
    type: 'Food & Beverage',
    description: 'A bakery offering fresh bread, pastries, and cakes.',
    location: '-26.2424, 27.8913',
    cover_img: '.',
    menu: [
      { item: 'Croissants', price: 'R20', description: 'Flaky and buttery croissants, perfect for breakfast.' },
      { item: 'Sourdough Bread', price: 'R40', description: 'Homemade sourdough bread with a tangy flavor.' },
      { item: 'Chocolate Cake', price: 'R60', description: 'Rich chocolate cake topped with ganache.' },
      { item: 'Fruit Tart', price: 'R50', description: 'A delicious tart filled with fresh fruit and custard.' },
    ],
    openingHours: 'Monday - Sunday: 7 AM - 6 PM',
    contact: '023 456 7890',
    website: 'http://sowetobakery.com',
  },
  {
    id: '16',
    name: 'Orlando West Ice Cream Parlour',
    type: 'Food & Beverage',
    description: 'A fun ice cream parlour serving a variety of flavors.',
    location: '-26.2435, 27.8901',
    cover_img: '.',
    menu: [
      { item: 'Vanilla Ice Cream', price: 'R30', description: 'Classic vanilla ice cream served in a cone or cup.' },
      { item: 'Chocolate Sundae', price: 'R40', description: 'Chocolate ice cream with hot fudge, whipped cream, and a cherry.' },
      { item: 'Strawberry Milkshake', price: 'R50', description: 'A creamy milkshake made with fresh strawberries and ice cream.' },
      { item: 'Waffle Cone', price: 'R35', description: 'A crunchy waffle cone filled with your choice of ice cream.' },
    ],
    openingHours: 'Monday - Sunday: 10 AM - 10 PM',
    contact: '024 567 8901',
    website: 'http://orlandowesticecreamparlour.com',
  }
];
export default businesses; // Ensure it is a default export
